"""empty message

Revision ID: 9182fb6ed67b
Revises: e88dd2cd9746
Create Date: 2022-01-10 20:40:38.257343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9182fb6ed67b'
down_revision = 'e88dd2cd9746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_work', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('start_work')

    # ### end Alembic commands ###
