"""empty message

Revision ID: e88dd2cd9746
Revises: 42e88312a43c
Create Date: 2022-01-10 20:40:26.256687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88dd2cd9746'
down_revision = '42e88312a43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('start_work')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_work', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
